#!/bin/sh
alias ka="killall"
alias mkd="mkdir -pv"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -rf"
alias f="vifm"
alias e="nvim"
alias v="vifmrun"
alias q="exit"
alias kt="tmux kill-server"
alias ch="chmod +x" 
alias la="exa --icons -a"
alias ll="exa --icons -l -a"
alias l="exa --icons"
alias l.="ls --color=auto -A |egrep'\.' "
alias cat="bat"
alias cd..="cd .."
alias grep="grep --color=auto"
alias egrep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias wget="wget -c"
alias upall="pkg update && pkg upgrade && apt update && apt upgrade && apt list --upgradable && python -m pip install --upgrade pip -y"
alias yt-dlp
alias yt-dlp="cd ~/Downloads/Videos && yt-dlp"
alias s="search.sh"
alias imgd="cd ~/Downloads/Images && wget -nd -r -p ./ -A jpeg,jpg,bmp,gif,png"


ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}
tmux
clear
neofetch --off
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.
vf() { fzf | xargs -r -I % $EDITOR % ;}
vs() { du -a ~/.local/bin/* | awk '{print $2}' | fzf | xargs -r -I % $EDITOR % ;}
